beetl:
  enabled: true
  suffix: html

spring:
  # 线程池配置
  task:
    execution:
      pool:
        # 核心线程池大小
        core-size: 10
        # 最大线程数
        max-size: 30
        # 活跃时间
        keep-alive: 60s
        # 队列容量
        queue-capacity: 50
      # 线程前缀
      thread-name-prefix: seckill-pool-task-
